### ISSUE TITLE
Training Strategies

### ISSUE THREAD

**Issue by mldemox** [ewrfcas/MVInpainter#3]
Thank you for your outstanding work, can you please publish the entire training process code?

**Comment by ewrfcas** [comment]
Both training and inference codes would be released soon (about one week).

**Comment by mldemox** [comment]
Ok, thanks for the update.

ewrfcas ***@***.***> 于2024年10月5日周六 21:39写道：

**Comment by mldemox** [comment]
Thank you for your work, I appreciate the interest in Reference Key&Value Concatenation (Ref-KV) mentioned in the paper, can you please tell me the exact location of the code implementation?

**Comment by ewrfcas** [comment]
> Thank you for your work, I appreciate the interest in Reference Key&Value Concatenation (Ref-KV) mentioned in the paper, can you please tell me the exact location of the code implementation?

https://github.com/ewrfcas/MVInpainter/blob/323d7f6ce3f73b0f263eb7f07dc48aefa6f27f34/models/attention_processor.py#L1248-L1250
